config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      post "add_comment"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :posts 
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
     before_filter :authenticate_user!, only: [:new, :create]

def new
    @post = Post.new
end

def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save!
        redirect_to @post
    else 
        render :new
    end
end

def update
    @posts = post.find params[:id]
    @posts.update post_params
    if @posts.save!
        redirect_to @post
    else 
        render :edit 
    end 
end

def show
    @post = Post.find params[:id]
    @comment = Comment.new
end

def edit
    posts = Post.find params[:id]
end

def update
    respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        else
            format.html { render :edit }
        end
    end
end
def add_comment
    @post = Post.find params[:id]
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to @post
end
    private
    
    def post_params
        params.require(:post).permit(:title,:body, :published)
        
    end
    def comment_params
        params.require(:comment).permit(:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container"> <%= yield %> </div>

</body>
</html>

app/views/posts/new.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :body %>
  <%= f.select :published, [[true, "Yes"], [false, "NO"]], { label: "To Published, Yes or No?:" } %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1>BlaCool!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" </a></p>
  <p>
  <strong>Message:</strong>
  <%= @post.body %>
</p>
<%= bootstrap_form_for @comment, url:  add_comment_post_path(@post) do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "Submit" %>
<% end %>
</div>

<p id="notice"><%= notice %></p>


<p>
  <strong>User:</strong>
  <%= @post.user.email%>
</p>



<% @post.comments.each do | comment|%>
<ul class="list-group">
  <li class="list-group-item comment-text"><%= comment.body%><%comment.user.email%> <%comment.created_at%></li>
</ul>

<%end%>